import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.models.mixins import UUIDPkMixin


class PasswordSetupToken(UUIDPkMixin, Base):
    """One-time "set your password" link for a local-auth user, generated by
    an admin and shared out-of-band (same manual-share philosophy as
    Team.tsx's ShareSignInLink — no outbound email sending). Looked up by
    the SHA-256 hash of the raw token, same as UserSession; not RLS-scoped
    for the same reason (looked up before any org context exists)."""

    __tablename__ = "password_setup_tokens"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    token_hash: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
