"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-31

Hand-written (not autogenerated) so RLS policies can be created precisely
alongside each tenant-scoped table. Run by the `migrate` one-off container
using the DB *owner* role — application containers connect as the separate
`dmarc_app` role instead, which is NOT the table owner, so
`FORCE ROW LEVEL SECURITY` actually applies to it (table owners are exempt
from RLS unless FORCE is set, but even FORCE doesn't bind a superuser —
`dmarc_app` is created NOSUPERUSER specifically so this holds).
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


# Tables whose rows belong to exactly one organization. Every one of these
# gets: ENABLE + FORCE ROW LEVEL SECURITY, and a policy allowing a row when
# either `app.current_org_id` matches, or `app.is_platform_admin` is set —
# see app/middleware/tenant_context.py for how those session vars get set.
# `user_sessions`/`platform_admin_sessions` are deliberately excluded (see
# app/models/session.py for why); so are `organizations` and
# `platform_admins`, which aren't tenant-scoped data in the first place.
TENANT_SCOPED_TABLES = [
    "mailbox_connections",
    "domains",
    "dkim_selectors",
    "dns_check_results",
    "dmarc_aggregate_reports",
    "dmarc_aggregate_records",
    "dmarc_forensic_reports",
    "tls_rpt_reports",
    "users",
    "job_runs",
]


def _enable_rls(table: str, org_column: str = "organization_id") -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON {table}
        USING (
            {org_column} = NULLIF(current_setting('app.current_org_id', true), '')::uuid
            OR current_setting('app.is_platform_admin', true) = 'true'
        )
        WITH CHECK (
            {org_column} = NULLIF(current_setting('app.current_org_id', true), '')::uuid
            OR current_setting('app.is_platform_admin', true) = 'true'
        )
        """
    )


def upgrade() -> None:
    bind = op.get_bind()

    organization_status = postgresql.ENUM(
        "pending_setup", "active", "suspended", name="organization_status"
    )
    consent_status = postgresql.ENUM("pending", "granted", "revoked", name="consent_status")
    sync_status = postgresql.ENUM("success", "error", name="sync_status")
    check_type = postgresql.ENUM(
        "spf", "dkim", "dmarc", "dmarcbis", "mta_sts", "tls_rpt", "dane", "mx", name="check_type"
    )
    check_status = postgresql.ENUM("pass", "warn", "fail", "error", name="check_status")
    disposition = postgresql.ENUM("none", "quarantine", "reject", name="disposition")
    auth_result = postgresql.ENUM("pass", "fail", name="auth_result")
    tls_rpt_policy_type = postgresql.ENUM(
        "tlsa", "sts", "no-policy-found", name="tls_rpt_policy_type"
    )
    user_role = postgresql.ENUM("org_admin", "member", name="user_role")
    user_status = postgresql.ENUM("active", "disabled", name="user_status")
    job_type = postgresql.ENUM("mailbox_poll", "dns_check", name="job_type")
    job_status = postgresql.ENUM("running", "success", "failure", name="job_status")

    for enum_type in [
        organization_status,
        consent_status,
        sync_status,
        check_type,
        check_status,
        disposition,
        auth_result,
        tls_rpt_policy_type,
        user_role,
        user_status,
        job_type,
        job_status,
    ]:
        enum_type.create(bind, checkfirst=True)
        # Without this, each sa.Column(..., enum_type) below would ALSO try
        # to auto-create the type as part of create_table's own DDL events,
        # duplicating the CREATE TYPE we just did explicitly above.
        enum_type.create_type = False

    now = sa.func.now()
    uuid_pk = lambda: sa.Column(  # noqa: E731
        "id", postgresql.UUID(as_uuid=True), primary_key=True
    )

    # --- organizations ---
    op.create_table(
        "organizations",
        uuid_pk(),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("entra_tenant_id", postgresql.UUID(as_uuid=True), nullable=True, unique=True),
        sa.Column("status", organization_status, nullable=False, server_default="pending_setup"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
    )

    # --- platform_admins ---
    op.create_table(
        "platform_admins",
        uuid_pk(),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
    )

    # --- mailbox_connections ---
    op.create_table(
        "mailbox_connections",
        uuid_pk(),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("mailbox_address", sa.String(320), nullable=False),
        sa.Column("consent_status", consent_status, nullable=False, server_default="pending"),
        sa.Column("consent_granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delta_link", sa.Text, nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_status", sync_status, nullable=True),
        sa.Column("last_sync_error", sa.Text, nullable=True),
        sa.Column("uses_custom_app", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("custom_client_id", sa.String(64), nullable=True),
        sa.Column("custom_client_secret_encrypted", sa.LargeBinary, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
    )

    # --- domains ---
    op.create_table(
        "domains",
        uuid_pk(),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "parent_domain_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("domains.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("name", sa.String(253), nullable=False),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.UniqueConstraint("organization_id", "name", name="uq_domains_org_name"),
    )
    op.create_index("ix_domains_organization_id", "domains", ["organization_id"])
    op.create_index("ix_domains_parent_domain_id", "domains", ["parent_domain_id"])

    # --- dkim_selectors ---
    op.create_table(
        "dkim_selectors",
        uuid_pk(),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "domain_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("domains.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("selector", sa.String(255), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.UniqueConstraint("domain_id", "selector", name="uq_dkim_selectors_domain_selector"),
    )
    op.create_index("ix_dkim_selectors_organization_id", "dkim_selectors", ["organization_id"])

    # --- dns_check_results ---
    op.create_table(
        "dns_check_results",
        uuid_pk(),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "domain_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("domains.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("check_type", check_type, nullable=False),
        sa.Column(
            "dkim_selector_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("dkim_selectors.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("subject", sa.String(255), nullable=True),
        sa.Column("status", check_status, nullable=False),
        sa.Column("summary", sa.Text, nullable=False),
        sa.Column("details", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("rule_version", sa.String(64), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_dns_check_results_domain_type_checked_at",
        "dns_check_results",
        ["domain_id", "check_type", sa.text("checked_at DESC")],
    )

    # --- dmarc_aggregate_reports ---
    op.create_table(
        "dmarc_aggregate_reports",
        uuid_pk(),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "domain_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("domains.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("report_id", sa.String(255), nullable=False),
        sa.Column("org_name", sa.String(255), nullable=False),
        sa.Column("email", sa.String(320), nullable=True),
        sa.Column("date_range_begin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_range_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("policy_published_domain", sa.String(253), nullable=False),
        sa.Column("policy_p", sa.String(32), nullable=True),
        sa.Column("policy_sp", sa.String(32), nullable=True),
        sa.Column("policy_pct", sa.Integer, nullable=True),
        sa.Column("policy_adkim", sa.String(8), nullable=True),
        sa.Column("policy_aspf", sa.String(8), nullable=True),
        sa.Column("source_message_id", sa.String(255), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.UniqueConstraint(
            "organization_id",
            "org_name",
            "report_id",
            "policy_published_domain",
            name="uq_dmarc_aggregate_reports_natural_key",
        ),
    )
    op.create_index(
        "ix_dmarc_aggregate_reports_domain_id", "dmarc_aggregate_reports", ["domain_id"]
    )

    # --- dmarc_aggregate_records ---
    op.create_table(
        "dmarc_aggregate_records",
        uuid_pk(),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "report_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("dmarc_aggregate_reports.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "domain_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("domains.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("source_ip", postgresql.INET, nullable=False),
        sa.Column("count", sa.Integer, nullable=False),
        sa.Column("disposition", disposition, nullable=False),
        sa.Column("dkim_result", auth_result, nullable=False),
        sa.Column("spf_result", auth_result, nullable=False),
        sa.Column("header_from", sa.String(253), nullable=False),
        sa.Column("envelope_from", sa.String(253), nullable=True),
        sa.Column("envelope_to", sa.String(253), nullable=True),
        sa.Column("auth_results", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("policy_evaluated_reasons", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_dmarc_aggregate_records_report_id", "dmarc_aggregate_records", ["report_id"])
    op.create_index("ix_dmarc_aggregate_records_source_ip", "dmarc_aggregate_records", ["source_ip"])
    op.create_index(
        "ix_dmarc_aggregate_records_domain_created_at",
        "dmarc_aggregate_records",
        ["domain_id", "created_at"],
    )

    # --- dmarc_forensic_reports ---
    op.create_table(
        "dmarc_forensic_reports",
        uuid_pk(),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "domain_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("domains.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("arrival_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_ip", postgresql.INET, nullable=True),
        sa.Column("reported_domain", sa.String(253), nullable=False),
        sa.Column("original_envelope_id", sa.String(255), nullable=True),
        sa.Column("dkim_domain", sa.String(253), nullable=True),
        sa.Column("spf_dns", sa.String(253), nullable=True),
        sa.Column("authentication_results", sa.Text, nullable=True),
        sa.Column("raw_message", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_dmarc_forensic_reports_domain_id", "dmarc_forensic_reports", ["domain_id"])
    op.create_index(
        "ix_dmarc_forensic_reports_created_at", "dmarc_forensic_reports", ["created_at"]
    )

    # --- tls_rpt_reports ---
    op.create_table(
        "tls_rpt_reports",
        uuid_pk(),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "domain_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("domains.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("org_name", sa.String(255), nullable=False),
        sa.Column("date_range_begin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_range_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("policy_type", tls_rpt_policy_type, nullable=False),
        sa.Column("policy_domain", sa.String(253), nullable=False),
        sa.Column("policy_string", postgresql.JSONB, nullable=True),
        sa.Column("summary_success_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("summary_failure_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("failure_details", postgresql.JSONB, nullable=True),
        sa.Column("source_message_id", sa.String(255), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "organization_id",
            "policy_domain",
            "org_name",
            "date_range_begin",
            "date_range_end",
            name="uq_tls_rpt_reports_natural_key",
        ),
    )
    op.create_index("ix_tls_rpt_reports_domain_id", "tls_rpt_reports", ["domain_id"])

    # --- users ---
    op.create_table(
        "users",
        uuid_pk(),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("entra_object_id", sa.String(64), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("display_name", sa.String(255), nullable=True),
        sa.Column("role", user_role, nullable=False, server_default="member"),
        sa.Column("status", user_status, nullable=False, server_default="active"),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=now, nullable=False),
        sa.UniqueConstraint("organization_id", "entra_object_id", name="uq_users_org_entra_object_id"),
    )

    # --- user_sessions (no RLS — see app/models/session.py) ---
    op.create_table(
        "user_sessions",
        uuid_pk(),
        sa.Column(
            "user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("session_token_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(64), nullable=True),
        sa.Column("user_agent", sa.String(512), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_user_sessions_user_id", "user_sessions", ["user_id"])

    # --- platform_admin_sessions (no RLS) ---
    op.create_table(
        "platform_admin_sessions",
        uuid_pk(),
        sa.Column(
            "platform_admin_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("platform_admins.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("session_token_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(64), nullable=True),
        sa.Column("user_agent", sa.String(512), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_platform_admin_sessions_platform_admin_id",
        "platform_admin_sessions",
        ["platform_admin_id"],
    )

    # --- job_runs ---
    op.create_table(
        "job_runs",
        uuid_pk(),
        sa.Column("job_type", job_type, nullable=False),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column(
            "domain_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("domains.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("status", job_status, nullable=False, server_default="running"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text, nullable=True),
        sa.Column("stats", postgresql.JSONB, nullable=True),
    )
    op.create_index("ix_job_runs_organization_id", "job_runs", ["organization_id"])
    op.create_index("ix_job_runs_started_at", "job_runs", ["started_at"])

    # --- row-level security ---
    for table in TENANT_SCOPED_TABLES:
        _enable_rls(table)

    # --- grant DML on everything to the runtime `dmarc_app` role, and make
    # future tables/sequences created by this (owner) role grant to it too.
    # The role itself is created by db/init/01-create-app-role.sh on first
    # container start; this just wires up privileges once tables exist. ---
    op.execute("GRANT USAGE ON SCHEMA public TO dmarc_app")
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dmarc_app"
    )
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dmarc_app")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dmarc_app"
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO dmarc_app"
    )


def downgrade() -> None:
    for table in reversed(TENANT_SCOPED_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")

    for table in [
        "job_runs",
        "platform_admin_sessions",
        "user_sessions",
        "users",
        "tls_rpt_reports",
        "dmarc_forensic_reports",
        "dmarc_aggregate_records",
        "dmarc_aggregate_reports",
        "dns_check_results",
        "dkim_selectors",
        "domains",
        "mailbox_connections",
        "platform_admins",
        "organizations",
    ]:
        op.drop_table(table)

    for enum_name in [
        "job_status",
        "job_type",
        "user_status",
        "user_role",
        "tls_rpt_policy_type",
        "auth_result",
        "disposition",
        "check_status",
        "check_type",
        "sync_status",
        "consent_status",
        "organization_status",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
